version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wishlist  # Создаст базу данных wishlist при запуске
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - postgres
    # ports:
    #   - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - app-network
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    networks:
      - postgres
    depends_on:
      - db

  # https://www.dmosk.ru/scripts.php?object=docker-compose-entrypoint
  # nginx-entrypoint:
  #   image: nginx
  #   hostname: nginx-entrypoint
  #   container_name: nginx-entrypoint
  #   restart: unless-stopped
  #   environment:
  #     TZ: "Europe/Moscow"
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./well-known:/usr/share/nginx/html
  #     - /opt/letsencrypt:/etc/letsencrypt
  #   networks:
  #     dnet:

# TODO: возможно нужно - https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
networks:
  postgres:
    driver: bridge
  app-network:
    name: app-network
    driver: bridge

volumes:
    postgres:
    pgadmin: